### PR TITLE
Lektura

### PR DESCRIPTION
**Pull request by MirelaZ**
I'm proofreading the text written on gray background, can you please explain the meaning of this sentence: Check if you are on any other page then admin and redirect accordingly.
Is "admin" used as a verb here, or should it be "Check if you are on any page other than admin and redirect accordingly", or maybe you had sth else in mind?

### CODE REVIEW

**Comment by dingo-d** [comment]
This should be reworded. The comment should be:

```php
* Check if the user is logged in, or is trying to access the front end page. 
* In either case, user should be redirected to the WordPress admin page.
```

**Comment by MirelaZ** [comment]
OK, thanks, just a few changes than:

/**
 * Check if the user is logged in or is trying to access the frontend page. 
 * In either case, the user should be redirected to the WordPress admin page.
 *
 * @return void
 */

**Comment by dingo-d** [comment]
I'm fine with that :) Can you add it in this PR? Thanks :+1:

**Comment by MirelaZ** [comment]
Sorry, I have no experience with GitHub, so I'm not sure how to do this exactly... Do I go to Files changed, click on the pencil to edit, and click commit, or is that completely wrong? :) I don't want to mess the text up or sth, could you please give me some instructions?

**Comment by dingo-d** [comment]
I can do it for you, no worries :) Plus don't worry about breaking things, this is what GitHub was made for. If you break something, you can easily revert the changes 🙂

**Pull request merged**
